### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidStopChanging' of undefined

### ISSUE THREAD

**Issue by jiku** [Joe-Withey/js-repl#1]
1. Install with apm as instructed or from preferences
2. Press ALT-R

**Atom Versions**: 1.10.2, 1.11.0-beta5
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [ramda-repl](https://github.com/Joe-Withey/js-repl) package, v0.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/dev/.atom/packages/ramda-repl/lib/ramda-repl.js:81

TypeError: Cannot read property 'dispose' of undefined
    at Object.quitRepl (/Users/dev/.atom/packages/ramda-repl/lib/ramda-repl.js:81:24)
    at Object.toggle (/Users/dev/.atom/packages/ramda-repl/lib/ramda-repl.js:40:25)
    at atom-workspace.ramdaReplToggle (/Users/dev/.atom/packages/ramda-repl/lib/ramda-repl.js:27:45)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -0:02.4.0 ramda-repl:toggle (atom-pane.pane.active)
```

I'll try on a different user or machine and see if it's permissions or something like that.

**Comment by Joe-Withey** [comment]
Hey thanks for the bug report.

Looking at the stack trace it appears to be throwing when the plugin is being toggled off. The commands also indicate the command is firing twice (possibly only when invoked once?). `quitRepl` is called when toggling the plugin off and we call `dispose` on the subscription to the `onDidStopChanging` event registered with the active text buffer. The check we make to determine whether we're toggling off or on is to check if the panel (the element where our evaluated code is displayed) is not null, somehow you have a panel === null and also no text change event registered. We can handle this process a lot better but your bug is still a mystery at this point. I'll try and reproduce the error and get to work. In the mean time if you'd like to take a look the code is very simple and you might be able to have some luck experimenting with the toggle functionality. It may be a good idea to use some explicit state variable instead of using the panel as a predicate.

**Comment by jiku** [comment]
It's working great now for both versions on the machine where I was having issues. Only impactful change  I can think of was a reboot. With it being panel related, it happened from shortcut, menu or palette invocation on both default untitled and JS documents, but I can only recreate it now by not having a file open. Closing but I'll let you know here (hopefully with a PR) if it reappears. Thanks for making it!
